packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: true
  msgpackr-extract: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@astryxdesign/core@0.1.7'
  - '@astryxdesign/theme-neutral@0.1.7'
  - '@astryxdesign/cli@0.1.7'
