packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@astryxdesign/core@0.1.7'
  - '@astryxdesign/theme-neutral@0.1.7'
  - '@astryxdesign/cli@0.1.7'
