const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

test('Vite bundles the same local Korean fonts without a network font service', () => {
    const web = path.join(__dirname, '..');
    const css = fs.readFileSync(path.join(web, 'src', 'app', 'globals.css'), 'utf8');
    const layout = fs.readFileSync(path.join(web, 'src', 'app', 'layout.tsx'), 'utf8');

    assert.doesNotMatch(layout, /next\/font/);
    assert.match(css, /NotoSansKR-Regular\.otf/);
    assert.match(css, /NotoSansKR-Bold\.otf/);
    assert.match(css, /--font-sans:\s*'TaeSlide Sans'/);
});

test('the slide canvas can draw the fonts the renderer resolves to', () => {
    // The editor renders the slide itself now, and a PPTX names its runs in
    // Korean. Without the same file the browser substitutes Malgun Gothic and
    // the canvas stops matching the export — the whole point of rendering live.
    const web = path.join(__dirname, '..');
    const css = fs.readFileSync(path.join(web, 'src', 'app', 'deck-fonts.css'), 'utf8');

    assert.match(fs.readFileSync(path.join(web, 'src', 'app', 'globals.css'), 'utf8'), /@import '\.\/deck-fonts\.css'/);
    assert.match(css, /font-family:\s*'NanumGothic'/);
    // Read off the font's own name table, not hand-written: a deck names its
    // runs in Korean and an internal font will too.
    assert.match(css, /font-family:\s*'나눔고딕'/);
    // WOFF2, not TTF: Chromium's webfont sanitiser rejects the original
    // NanumGothic.ttf outright, and the rebuilt tables are a third the size.
    for (const rule of css.match(/@font-face\s*\{[^}]*\}/g) || []) {
        assert.doesNotMatch(rule, /\.ttf|\.otf/, `not converted for the browser: ${rule}`);
    }
    for (const file of ['NanumGothic.woff2', 'NanumGothicBold.woff2', 'LICENSE-nanum.txt']) {
        assert.ok(fs.existsSync(path.join(web, 'public', 'fonts', file)), `missing ${file}`);
    }
});

test('the font picker offers what is installed, not a hand-kept list', () => {
    const web = path.join(__dirname, '..');
    const editor = fs.readFileSync(path.join(web, 'src', 'app', 'editor', '[id]', 'page.tsx'), 'utf8');

    assert.match(editor, /import \{ DECK_FONTS \} from '@\/lib\/deck-fonts'/);
    assert.match(editor, /const FONT_CHOICES = \[\.\.\.DECK_FONTS/);
    // The toolbar offers the installed families for whatever is selected.
    assert.match(editor, /fontChoicesWith\(activeFormat\.fontFamily\)/);
    // Neither makes you spell a family into a free-text box any more.
    assert.doesNotMatch(editor, /글꼴<input/);
    // A deck can name a font nobody installed; dropping it from the list would
    // silently retype the object the moment the panel opened.
    assert.match(editor, /function fontChoicesWith/);

    const generated = fs.readFileSync(path.join(web, 'src', 'lib', 'deck-fonts.ts'), 'utf8');
    assert.match(generated, /Generated by scripts\/install-fonts\.mjs/);
    assert.match(generated, /나눔고딕/);
});
