const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');

test('TaeSlide editor persists generic HTML object styles', () => {
    const root = path.join(__dirname, '..', 'src');
    const editor = fs.readFileSync(path.join(root, 'app', 'editor', '[id]', 'page.tsx'), 'utf8');
    const layout = fs.readFileSync(path.join(root, 'app', 'layout.tsx'), 'utf8');

    assert.match(editor, /function updateHtmlObject/);
    assert.match(editor, /function htmlTextElements/);
    assert.match(editor, /const generatedText/);
    assert.match(editor, /AI 텍스트/);
    assert.match(editor, /fontSize/);
    assert.match(editor, /backgroundColor/);
    assert.match(editor, /addHtmlShape/);
    assert.match(editor, /addHtmlTable/);
    assert.match(editor, /addHtmlImage/);
    assert.match(editor, /addHtmlList/);
    assert.match(editor, /borderColor/);
    assert.match(editor, /fontFamily/);
    assert.match(editor, /fontWeight/);
    assert.match(editor, /fontStyle/);
    assert.match(editor, /textDecoration/);
    assert.match(editor, /ribbonTab/);
    assert.match(editor, /deleteHtmlObject/);
    assert.match(editor, /deleteSelectedHtmlObject/);
    assert.match(editor, /duplicateSelectedHtmlObject/);
    assert.match(editor, /function duplicateHtmlObject/);
    assert.match(editor, /function setHtmlList/);
    assert.match(editor, /setSelectedHtmlList/);
    assert.match(editor, /const EDITOR_COLORS/);
    assert.match(editor, /function ColorSwatches/);
    assert.match(editor, /\$\{label\} 메뉴/);
    assert.match(editor, /슬라이드 텍스트 직접 편집/);
    assert.match(editor, /persistHistoryState/);
    assert.match(editor, /clearTimeout\(saveTimeoutRef\.current\)/);
    assert.doesNotMatch(editor, /onBlur=\{\(\) => \{ setInlineTextIndex\(null\); onSave\(\); \}\}/);
    assert.match(editor, /data-html-editor-frame/);
    assert.match(editor, /document\.body\.contentEditable = 'true'/);
    assert.match(editor, /contentEditable = 'true'/);
    assert.match(editor, /dataset\.taeslideEditorIndex/);
    assert.match(editor, /selectionchange/);
    assert.match(editor, /execCommand\(/);
    assert.match(editor, /event\.altKey/);
    assert.match(editor, /pointermove/);
    assert.match(editor, /selectedElement/);
    assert.match(editor, /selectedElement\.remove\(\)/);
    assert.match(editor, /candidate\?\.nodeType === 1/);
    assert.ok(editor.indexOf('if (content.html)') < editor.indexOf('const startHtmlTransform'));
    assert.match(editor, /startSlideSwipe/);
    assert.match(editor, /onNavigate/);
    assert.match(editor, /kind = 'rectangle'/);
    assert.match(editor, /화살표/);
    assert.match(editor, /const SHAPE_GROUPS/);
    assert.match(editor, /const SHAPE_GROUPS = ALL_SHAPE_GROUPS/);
    assert.match(editor, /const LINE_OPTIONS/);
    assert.match(editor, /arrowLine/);
    assert.match(editor, /doubleArrowLine/);
    assert.match(editor, /function ShapePickerGlyph/);
    assert.match(editor, /shapeStyle\(kind\)/);
    assert.match(editor, /box-shadow:0 0 0 2px/);
    assert.match(editor, /flowChartProcess/);
    assert.match(editor, /curvedConnector5/);
    assert.match(editor, /overflow-visible border-b bg-white/);
    assert.match(editor, /w-\[1100px\] min-w-\[960px\]/);
assert.match(editor, /isFocusMode/);
assert.match(editor, /집중 보기/);
assert.match(editor, /window\.innerWidth < 1180/);
assert.match(editor, /isLeftPanelOpen/);
assert.match(editor, /isRightPanelOpen/);
assert.match(editor, /슬라이드 패널 접기/);
assert.match(editor, /AI 패널 접기/);
    assert.match(editor, /const nextIndex = getHtmlTextFields\(selectedSlide\.content\.html\)\.length/);
    assert.match(editor, /setRibbonTab\('home'\)/);
    assert.match(editor, /e\.key === 'Delete'/);
    assert.match(editor, /selectedNativeObjectId/);
    assert.match(editor, /updateNativeObject/);
    assert.match(editor, /nativeObjects/);
    assert.match(editor, /data-native-object/);
    assert.match(editor, /selectedNativeObject\.fontFamily/);
    assert.match(editor, /fontSize: Number/);
    assert.match(editor, /bold:/);
    assert.match(editor, /italic:/);
    assert.match(layout, /TaeSlide/);
});
