#!/usr/bin/env node
/**
 * Install deck fonts so the editor and the renderer draw the same glyphs.
 *
 * Drop .ttf/.otf/.woff2 files into `fonts/` at the repo root and run this. It
 * converts what needs converting, writes the @font-face rules, and registers
 * every family in the editor's font picker.
 *
 * Two places need the font, which is the part that is easy to get wrong. The
 * browser draws the editing canvas; LibreOffice and Chromium inside the
 * renderer draw the preview, the PDF and the exported PPTX. Ship to only one
 * and the screen stops matching the file.
 *
 * Chromium runs a webfont through its own sanitiser and rejects plenty of
 * otherwise-valid TTFs — the Debian NanumGothic among them, after all 4.7MB
 * have arrived. Converting to WOFF2 rebuilds the tables and, incidentally,
 * cuts a Korean font to about a third of its size.
 *
 *   node scripts/install-fonts.mjs
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE_DIR = path.join(ROOT, 'fonts');
const WEB_FONTS = path.join(ROOT, 'apps', 'web', 'public', 'fonts');
const GENERATED_CSS = path.join(ROOT, 'apps', 'web', 'src', 'app', 'deck-fonts.css');
const GENERATED_TS = path.join(ROOT, 'apps', 'web', 'src', 'lib', 'deck-fonts.ts');
const RENDERER_FONTS = path.join(ROOT, 'docker', 'fonts');

const BANNER = '/* Generated by scripts/install-fonts.mjs — edit fonts/ and re-run, not this file. */\n';

/** Weight and style read off the filename, the way font vendors name them. */
function faceOf(basename) {
    const lower = basename.toLowerCase();
    const weight = /(black|heavy)/.test(lower) ? 900
        : /extrabold|ultrabold/.test(lower) ? 800
            : /semibold|demibold/.test(lower) ? 600
                : /bold/.test(lower) ? 700
                    : /light/.test(lower) ? 300
                        : /thin/.test(lower) ? 100
                            : 400;
    const style = /italic|oblique/.test(lower) ? 'italic' : 'normal';
    // "NanumGothicBold" and "NanumGothic" are one family at two weights.
    const family = basename.replace(/[-_ ]?(black|heavy|extrabold|ultrabold|semibold|demibold|bold|light|thin|regular|italic|oblique)/gi, '') || basename;
    return { family, weight, style };
}

const PY_PROCESS = `
import json, sys
from fontTools.ttLib import TTFont
font = TTFont("/tmp/in-font")
# Name ID 1 in every language the vendor shipped. A Korean font carries its
# Hangul name here, and that is the name a PPTX run uses — so declaring only the
# Latin one leaves the deck asking for a family the browser has never heard of.
names = []
for record in font["name"].names:
    if record.nameID in (1, 16):
        try:
            value = record.toUnicode().strip()
        except UnicodeDecodeError:
            continue
        if value and value not in names:
            names.append(value)
if font.flavor != "woff2":
    font.flavor = "woff2"
    font.save("/tmp/out-font.woff2")
else:
    import shutil; shutil.copy("/tmp/in-font", "/tmp/out-font.woff2")
print(json.dumps(names))
`;

/**
 * Convert to WOFF2 and read back every family name the font answers to.
 *
 * fonttools lives in the renderer image already, so there is no second
 * toolchain to install on a closed network.
 */
function processFont(source, destination) {
    const container = execFileSync('docker', ['compose', 'ps', '-q', 'renderer'], { cwd: ROOT }).toString().trim();
    if (!container) throw new Error('renderer container is not running — start it with `docker compose up -d renderer`');
    execFileSync('docker', ['cp', source, `${container}:/tmp/in-font`], { cwd: ROOT });
    const output = execFileSync('docker', ['exec', container, 'python', '-c', PY_PROCESS], { cwd: ROOT }).toString();
    execFileSync('docker', ['cp', `${container}:/tmp/out-font.woff2`, destination], { cwd: ROOT });
    return JSON.parse(output.trim().split('\n').pop());
}

function main() {
    if (!fs.existsSync(SOURCE_DIR)) {
        fs.mkdirSync(SOURCE_DIR, { recursive: true });
        console.log(`Created ${path.relative(ROOT, SOURCE_DIR)}. Put your .ttf/.otf/.woff2 files there and run this again.`);
        return;
    }
    const sources = fs.readdirSync(SOURCE_DIR).filter((name) => /\.(ttf|otf|woff2)$/i.test(name));
    if (!sources.length) {
        console.log(`No fonts in ${path.relative(ROOT, SOURCE_DIR)}. Put your .ttf/.otf/.woff2 files there and run this again.`);
        return;
    }

    fs.mkdirSync(WEB_FONTS, { recursive: true });
    fs.mkdirSync(RENDERER_FONTS, { recursive: true });

    const faces = [];
    for (const name of sources) {
        const source = path.join(SOURCE_DIR, name);
        const base = path.basename(name).replace(/\.(ttf|otf|woff2)$/i, '');
        const webFile = `${base}.woff2`;
        const webTarget = path.join(WEB_FONTS, webFile);

        console.log(`installing ${name}`);
        const declared = processFont(source, webTarget);
        // The renderer wants the original outline format, which fontconfig reads.
        fs.copyFileSync(source, path.join(RENDERER_FONTS, name));

        const guessed = faceOf(base);
        // Every name the font answers to, so a deck naming it in Korean resolves.
        const aliases = [...new Set([guessed.family, ...declared])];
        faces.push({ file: webFile, ...guessed, aliases });
    }

    const families = [...new Set(faces.flatMap((face) => face.aliases))].sort();
    const rules = faces.flatMap(({ aliases, weight, style, file }) => aliases.map((family) =>
        `@font-face { font-family: '${family}'; src: url('/fonts/${file}') format('woff2'); font-weight: ${weight}; font-style: ${style}; font-display: block; }`));
    fs.writeFileSync(GENERATED_CSS, `${BANNER}${rules.join('\n')}\n`);

    fs.writeFileSync(GENERATED_TS,
        `${BANNER}\n/** Families installed from fonts/, offered in the editor's font picker. */\n`
        + `export const DECK_FONTS: readonly string[] = ${JSON.stringify(families, null, 4)};\n`);

    console.log(`\ninstalled ${faces.length} file(s), ${families.length} famil(y|ies): ${families.join(', ')}`);
    console.log(`  browser  -> ${path.relative(ROOT, WEB_FONTS)}`);
    console.log(`  renderer -> ${path.relative(ROOT, RENDERER_FONTS)}  (rebuild it: docker compose up -d --build renderer)`);
}

main();
