/* Generated by scripts/install-fonts.mjs — edit fonts/ and re-run, not this file. */

/** Families installed from fonts/, offered in the editor's font picker. */
export const DECK_FONTS: readonly string[] = [
    "NanumGothic",
    "나눔고딕"
];
